### ISSUE TITLE
I made something and was wondering if it was relevant here

### ISSUE THREAD

**Issue by Rested** [erwanp/awesome-spectra#5]
Hey I made a little js library for visual atomic emission spectra and was wondering if it was relevant here 
https://github.com/Rested/react-emission-spectra

**Comment by erwanp** [comment]
Hello @Rested ! Nice project, I think it should definitly be included. Do you want to submit a PR and create a "Visualization" category, for instance ?

**Comment by Rested** [comment]
Thanks! I made a PR #6  feel free to change any of the wording!
